### ISSUE TITLE
Unable to use message formatting

### ISSUE THREAD

**Issue by ehsannarmani** [BorisTestov/tg_sender_action#1]
I cant use't message formatting such as markdown or html in message for example 

`(backtick)Text(backtick)`

Or
`<code>Test</code>`

**Comment by BorisTestov** [comment]
Hi @ehsannarmani! Thanks for letting me know. I've updated the code and the Docker image; now it should work fine. Telegram supports three different parse modes: `HTML`, `MARKDOWN`, and `MARKDOWNV2`. If no parse mode is set, or the value is incorrect (not one of the values listed above), then plain text will be sent.

Also, keep in mind that Telegram doesn't support all HTML/markdown features. You can see the supported syntax [here](https://core.telegram.org/bots/api#formatting-options).

**Comment by ehsannarmani** [comment]
@BorisTestov Thank you for your quick reply, i've tried now the latest version, it seems working fine, thank you so much for paying attention to this issue and fixing it.
